iI am testing my yaml file in my new projects
ok i am working my yaml file and all work done in yaml file

i have comeing in my all best in the world in the all tesing
i am dhiraj pawar i have commapleted my work in between to time 
i will go ing o my all time in my classroom
 the all repo is a not a master repo but you can created new branch in the master branch 
 and we also created new more than one branch in from master 
 i have done any type of work in a master branch but i can not directly changes in master 
 branch i will work in master branch bur not changes in a master branch


first we can created new branch in master branch and then we can written code in new branch that 
branch created in a master branch 
then you can add this code and then you can commit these code in master branch and then we are mearge in master 
and we are add in that code in master branch and then we will connected in a new branch and all 
brannches in a master branch i will done in my called i will commited that is it is my all 
future plan

but i am very lucy for in my all command and my all work in the non stop work
but i will commanly commpound in my all non stop work but i will love in my all parents and 
and all my colligas i will done in my all pattanjali working area git it is my all types works in done
but i will camming in my all sent work 
